# Generated by Django 2.2 on 2019-04-26 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rekognition.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userImage', models.ImageField(blank=True, null=True, upload_to=rekognition.models.get_image_path)),
                ('userFirstname', models.CharField(max_length=100)),
                ('userLastname', models.CharField(max_length=100)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
