# Generated by Django 2.2 on 2019-04-29 10:26

from django.db import migrations, models
import rekognition.models


class Migration(migrations.Migration):

    dependencies = [
        ('rekognition', '0002_auto_20190429_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userImage',
            field=models.ImageField(blank=True, null=True, upload_to=rekognition.models.get_image_path),
        ),
    ]
