# Generated by Django 2.2 on 2019-05-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekognition', '0004_auto_20190429_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onBuilding',
            field=models.BooleanField(default=False),
        ),
    ]
